# Generated by Django 3.2.7 on 2021-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('rank', models.IntegerField(default=0, verbose_name='ランク')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='コメント')),
            ],
        ),
    ]
